name: Pinois's blog
description: Music & Technology
meta_description: "Loïc Lepinois's blog"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]

paginate: 20
paginate_path: "page:num"
baseurl: /
domain_name: 'http://pinois.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'pinois'

# Details for the RSS feed generator
url:            'http://pinois.github.io'
author:         'Pinois'
authorTwitter:  'elpinois'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
